source 'https://rubygems.org'

gem 'sinatra'
gem 'warden'
gem 'bcrypt'
gem 'mysql2'
gem 'sinatra-activerecord'
gem 'rake'
gem 'thin'
gem 'shotgun'
gem 'jbuilder'
gem 'tilt-jbuilder'
gem 'require_all'
gem 'factory_girl'
gem 'json'

group :development, :test do
  gem 'rspec'
  gem 'racksh'
  gem 'rubocop'
  gem 'database_cleaner'
  gem 'mocha'
  gem 'pry'
  gem 'rack-test'
end
